package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
public class AddInDefinitionsListXml {

	private AddInDefinitionXml[] definitionsField;

	/**
	 * <remarks/>
	 */
	public final AddInDefinitionXml[] getdefinitions() {
		return this.definitionsField;
	}

	public final void setdefinitions(AddInDefinitionXml[] value) {
		this.definitionsField = value;
	}

}