package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
public class AddInDefinitionXml {

	private String typeNameField;

	private boolean enabledField;

	private String captionField;

	private String descriptionField;

	private String versionField;

	private String sourceField;

	/**
	 * <remarks/>
	 */
	public final String gettypeName() {
		return this.typeNameField;
	}

	public final void settypeName(String value) {
		this.typeNameField = value;
	}

	/**
	 * <remarks/>
	 */
	public final boolean getenabled() {
		return this.enabledField;
	}

	public final void setenabled(boolean value) {
		this.enabledField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getcaption() {
		return this.captionField;
	}

	public final void setcaption(String value) {
		this.captionField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getdescription() {
		return this.descriptionField;
	}

	public final void setdescription(String value) {
		this.descriptionField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getversion() {
		return this.versionField;
	}

	public final void setversion(String value) {
		this.versionField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getsource() {
		return this.sourceField;
	}

	public final void setsource(String value) {
		this.sourceField = value;
	}
}