package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class AddInDefinitionsListXml.
 */
public class AddInDefinitionsListXml {

	/** The definitions field. */
	private AddInDefinitionXml[] definitionsField;

	/**
	 * Gets the definitions.
	 *
	 * @return the definitions
	 */
	public final AddInDefinitionXml[] getdefinitions() {
		return this.definitionsField;
	}

	/**
	 * Sets the definitions.
	 *
	 * @param value the new definitions
	 */
	public final void setdefinitions(AddInDefinitionXml[] value) {
		this.definitionsField = value;
	}

}