package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class AddInDefinitionXml.
 */
public class AddInDefinitionXml {

	/** The type name field. */
	private String typeNameField;

	/** The enabled field. */
	private boolean enabledField;

	/** The caption field. */
	private String captionField;

	/** The description field. */
	private String descriptionField;

	/** The version field. */
	private String versionField;

	/** The source field. */
	private String sourceField;

	/**
	 * Gets the type name.
	 *
	 * @return the type name
	 */
	public final String gettypeName() {
		return this.typeNameField;
	}

	/**
	 * Sets the type name.
	 *
	 * @param value the new type name
	 */
	public final void settypeName(String value) {
		this.typeNameField = value;
	}

	/**
	 * Gets the enabled.
	 *
	 * @return the enabled
	 */
	public final boolean getenabled() {
		return this.enabledField;
	}

	/**
	 * Sets the enabled.
	 *
	 * @param value the new enabled
	 */
	public final void setenabled(boolean value) {
		this.enabledField = value;
	}

	/**
	 * Gets the caption.
	 *
	 * @return the caption
	 */
	public final String getcaption() {
		return this.captionField;
	}

	/**
	 * Sets the caption.
	 *
	 * @param value the new caption
	 */
	public final void setcaption(String value) {
		this.captionField = value;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	public final String getdescription() {
		return this.descriptionField;
	}

	/**
	 * Sets the description.
	 *
	 * @param value the new description
	 */
	public final void setdescription(String value) {
		this.descriptionField = value;
	}

	/**
	 * Gets the version.
	 *
	 * @return the version
	 */
	public final String getversion() {
		return this.versionField;
	}

	/**
	 * Sets the version.
	 *
	 * @param value the new version
	 */
	public final void setversion(String value) {
		this.versionField = value;
	}

	/**
	 * Gets the source.
	 *
	 * @return the source
	 */
	public final String getsource() {
		return this.sourceField;
	}

	/**
	 * Sets the source.
	 *
	 * @param value the new source
	 */
	public final void setsource(String value) {
		this.sourceField = value;
	}
}