package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
public class ClientRepositoryXml {

	private DateTimeOffsetXml addedDtField;

	private DateTimeOffsetXml lastContactDtField;

	private String idField;

	private String hostNameField;

	private String computerKeyField;

	private long currentSessionsVersionField;

	private boolean currentSessionsVersionFieldSpecified;

	private String publicKeyField;

	private ClientRepositoryStatusXml statusField = ClientRepositoryStatusXml.values()[0];

	private boolean statusFieldSpecified;

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getaddedDt() {
		return this.addedDtField;
	}

	public final void setaddedDt(DateTimeOffsetXml value) {
		this.addedDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getlastContactDt() {
		return this.lastContactDtField;
	}

	public final void setlastContactDt(DateTimeOffsetXml value) {
		this.lastContactDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String gethostName() {
		return this.hostNameField;
	}

	public final void sethostName(String value) {
		this.hostNameField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getcomputerKey() {
		return this.computerKeyField;
	}

	public final void setcomputerKey(String value) {
		this.computerKeyField = value;
	}

	/**
	 * <remarks/>
	 */
	public final long getcurrentSessionsVersion() {
		return this.currentSessionsVersionField;
	}

	public final void setcurrentSessionsVersion(long value) {
		this.currentSessionsVersionField = value;
	}

	/**
	 * <remarks/>
	 */
	public final boolean getcurrentSessionsVersionSpecified() {
		return this.currentSessionsVersionFieldSpecified;
	}

	public final void setcurrentSessionsVersionSpecified(boolean value) {
		this.currentSessionsVersionFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getpublicKey() {
		return this.publicKeyField;
	}

	public final void setpublicKey(String value) {
		this.publicKeyField = value;
	}

	/**
	 * <remarks/>
	 */
	public final ClientRepositoryStatusXml getstatus() {
		return this.statusField;
	}

	public final void setstatus(ClientRepositoryStatusXml value) {
		this.statusField = value;
	}

	/**
	 * <remarks/>
	 */
	public final boolean getstatusSpecified() {
		return this.statusFieldSpecified;
	}

	public final void setstatusSpecified(boolean value) {
		this.statusFieldSpecified = value;
	}

}