package com.onloupe.core.server.data;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class ClientRepositoryXml.
 */
public class ClientRepositoryXml {

	/** The added dt field. */
	private DateTimeOffsetXml addedDtField;

	/** The last contact dt field. */
	private DateTimeOffsetXml lastContactDtField;

	/** The id field. */
	private String idField;

	/** The host name field. */
	private String hostNameField;

	/** The computer key field. */
	private String computerKeyField;

	/** The current sessions version field. */
	private long currentSessionsVersionField;

	/** The current sessions version field specified. */
	private boolean currentSessionsVersionFieldSpecified;

	/** The public key field. */
	private String publicKeyField;

	/** The status field. */
	private ClientRepositoryStatusXml statusField = ClientRepositoryStatusXml.values()[0];

	/** The status field specified. */
	private boolean statusFieldSpecified;

	/**
	 * Gets the added dt.
	 *
	 * @return the added dt
	 */
	public final DateTimeOffsetXml getaddedDt() {
		return this.addedDtField;
	}

	/**
	 * Sets the added dt.
	 *
	 * @param value the new added dt
	 */
	public final void setaddedDt(DateTimeOffsetXml value) {
		this.addedDtField = value;
	}

	/**
	 * Gets the last contact dt.
	 *
	 * @return the last contact dt
	 */
	public final DateTimeOffsetXml getlastContactDt() {
		return this.lastContactDtField;
	}

	/**
	 * Sets the last contact dt.
	 *
	 * @param value the new last contact dt
	 */
	public final void setlastContactDt(DateTimeOffsetXml value) {
		this.lastContactDtField = value;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public final String getid() {
		return this.idField;
	}

	/**
	 * Sets the id.
	 *
	 * @param value the new id
	 */
	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * Gets the host name.
	 *
	 * @return the host name
	 */
	public final String gethostName() {
		return this.hostNameField;
	}

	/**
	 * Sets the host name.
	 *
	 * @param value the new host name
	 */
	public final void sethostName(String value) {
		this.hostNameField = value;
	}

	/**
	 * Gets the computer key.
	 *
	 * @return the computer key
	 */
	public final String getcomputerKey() {
		return this.computerKeyField;
	}

	/**
	 * Sets the computer key.
	 *
	 * @param value the new computer key
	 */
	public final void setcomputerKey(String value) {
		this.computerKeyField = value;
	}

	/**
	 * Gets the current sessions version.
	 *
	 * @return the current sessions version
	 */
	public final long getcurrentSessionsVersion() {
		return this.currentSessionsVersionField;
	}

	/**
	 * Sets the current sessions version.
	 *
	 * @param value the new current sessions version
	 */
	public final void setcurrentSessionsVersion(long value) {
		this.currentSessionsVersionField = value;
	}

	/**
	 * Gets the current sessions version specified.
	 *
	 * @return the current sessions version specified
	 */
	public final boolean getcurrentSessionsVersionSpecified() {
		return this.currentSessionsVersionFieldSpecified;
	}

	/**
	 * Sets the current sessions version specified.
	 *
	 * @param value the new current sessions version specified
	 */
	public final void setcurrentSessionsVersionSpecified(boolean value) {
		this.currentSessionsVersionFieldSpecified = value;
	}

	/**
	 * Gets the public key.
	 *
	 * @return the public key
	 */
	public final String getpublicKey() {
		return this.publicKeyField;
	}

	/**
	 * Sets the public key.
	 *
	 * @param value the new public key
	 */
	public final void setpublicKey(String value) {
		this.publicKeyField = value;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	public final ClientRepositoryStatusXml getstatus() {
		return this.statusField;
	}

	/**
	 * Sets the status.
	 *
	 * @param value the new status
	 */
	public final void setstatus(ClientRepositoryStatusXml value) {
		this.statusField = value;
	}

	/**
	 * Gets the status specified.
	 *
	 * @return the status specified
	 */
	public final boolean getstatusSpecified() {
		return this.statusFieldSpecified;
	}

	/**
	 * Sets the status specified.
	 *
	 * @param value the new status specified
	 */
	public final void setstatusSpecified(boolean value) {
		this.statusFieldSpecified = value;
	}

}