package com.onloupe.core.server.data;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
public class DateTimeOffsetXml {

	private LocalDateTime dateTimeField = LocalDateTime.MIN;

	private int offsetField;

	/**
	 * <remarks/>
	 */
	public final LocalDateTime getDateTime() {
		return this.dateTimeField;
	}

	public final void setDateTime(LocalDateTime value) {
		this.dateTimeField = value;
	}

	/**
	 * <remarks/>
	 */
	public final int getOffset() {
		return this.offsetField;
	}

	public final void setOffset(int value) {
		this.offsetField = value;
	}

}