package com.onloupe.core.server.data;

import java.time.LocalDateTime;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class DateTimeOffsetXml.
 */
public class DateTimeOffsetXml {

	/** The date time field. */
	private LocalDateTime dateTimeField = LocalDateTime.MIN;

	/** The offset field. */
	private int offsetField;

	/**
	 * Gets the date time.
	 *
	 * @return the date time
	 */
	public final LocalDateTime getDateTime() {
		return this.dateTimeField;
	}

	/**
	 * Sets the date time.
	 *
	 * @param value the new date time
	 */
	public final void setDateTime(LocalDateTime value) {
		this.dateTimeField = value;
	}

	/**
	 * Gets the offset.
	 *
	 * @return the offset
	 */
	public final int getOffset() {
		return this.offsetField;
	}

	/**
	 * Sets the offset.
	 *
	 * @param value the new offset
	 */
	public final void setOffset(int value) {
		this.offsetField = value;
	}

}