package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

public class FolderDetailXml {

	private DateTimeOffsetXml updatedDtField;

	private SessionXml[] sessionsField;

	private SessionXml[] addedSessionsField;

	private SessionXml[] removedSessionsField;

	private String selectionCriteriaXmlField;

	private String nameField;

	private String parentFolderIdField;

	private FolderTypeXml folderTypeField = FolderTypeXml.values()[0];

	private String updateUserField;

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getupdatedDt() {
		return this.updatedDtField;
	}

	public final void setupdatedDt(DateTimeOffsetXml value) {
		this.updatedDtField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] sessions
	public final SessionXml[] getsessions() {
		return this.sessionsField;
	}

	public final void setsessions(SessionXml[] value) {
		this.sessionsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] addedSessions
	public final SessionXml[] getaddedSessions() {
		return this.addedSessionsField;
	}

	public final void setaddedSessions(SessionXml[] value) {
		this.addedSessionsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] removedSessions
	public final SessionXml[] getremovedSessions() {
		return this.removedSessionsField;
	}

	public final void setremovedSessions(SessionXml[] value) {
		this.removedSessionsField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getselectionCriteriaXml() {
		return this.selectionCriteriaXmlField;
	}

	public final void setselectionCriteriaXml(String value) {
		this.selectionCriteriaXmlField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string name
	public final String getname() {
		return this.nameField;
	}

	public final void setname(String value) {
		this.nameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string parentFolderId
	public final String getparentFolderId() {
		return this.parentFolderIdField;
	}

	public final void setparentFolderId(String value) {
		this.parentFolderIdField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public FolderTypeXml folderType
	public final FolderTypeXml getfolderType() {
		return this.folderTypeField;
	}

	public final void setfolderType(FolderTypeXml value) {
		this.folderTypeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string updateUser
	public final String getupdateUser() {
		return this.updateUserField;
	}

	public final void setupdateUser(String value) {
		this.updateUserField = value;
	}

}