package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class FolderDetailXml.
 */
public class FolderDetailXml {

	/** The updated dt field. */
	private DateTimeOffsetXml updatedDtField;

	/** The sessions field. */
	private SessionXml[] sessionsField;

	/** The added sessions field. */
	private SessionXml[] addedSessionsField;

	/** The removed sessions field. */
	private SessionXml[] removedSessionsField;

	/** The selection criteria xml field. */
	private String selectionCriteriaXmlField;

	/** The name field. */
	private String nameField;

	/** The parent folder id field. */
	private String parentFolderIdField;

	/** The folder type field. */
	private FolderTypeXml folderTypeField = FolderTypeXml.values()[0];

	/** The update user field. */
	private String updateUserField;

	/**
	 * Gets the updated dt.
	 *
	 * @return the updated dt
	 */
	public final DateTimeOffsetXml getupdatedDt() {
		return this.updatedDtField;
	}

	/**
	 * Sets the updated dt.
	 *
	 * @param value the new updated dt
	 */
	public final void setupdatedDt(DateTimeOffsetXml value) {
		this.updatedDtField = value;
	}

	/**
	 * Gets the sessions.
	 *
	 * @return the sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] sessions
	public final SessionXml[] getsessions() {
		return this.sessionsField;
	}

	/**
	 * Sets the sessions.
	 *
	 * @param value the new sessions
	 */
	public final void setsessions(SessionXml[] value) {
		this.sessionsField = value;
	}

	/**
	 * Gets the added sessions.
	 *
	 * @return the added sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] addedSessions
	public final SessionXml[] getaddedSessions() {
		return this.addedSessionsField;
	}

	/**
	 * Sets the added sessions.
	 *
	 * @param value the new added sessions
	 */
	public final void setaddedSessions(SessionXml[] value) {
		this.addedSessionsField = value;
	}

	/**
	 * Gets the removed sessions.
	 *
	 * @return the removed sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("session", IsNullable=false)] public SessionXml[] removedSessions
	public final SessionXml[] getremovedSessions() {
		return this.removedSessionsField;
	}

	/**
	 * Sets the removed sessions.
	 *
	 * @param value the new removed sessions
	 */
	public final void setremovedSessions(SessionXml[] value) {
		this.removedSessionsField = value;
	}

	/**
	 * Gets the selection criteria xml.
	 *
	 * @return the selection criteria xml
	 */
	public final String getselectionCriteriaXml() {
		return this.selectionCriteriaXmlField;
	}

	/**
	 * Sets the selection criteria xml.
	 *
	 * @param value the new selection criteria xml
	 */
	public final void setselectionCriteriaXml(String value) {
		this.selectionCriteriaXmlField = value;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string name
	public final String getname() {
		return this.nameField;
	}

	/**
	 * Sets the name.
	 *
	 * @param value the new name
	 */
	public final void setname(String value) {
		this.nameField = value;
	}

	/**
	 * Gets the parent folder id.
	 *
	 * @return the parent folder id
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string parentFolderId
	public final String getparentFolderId() {
		return this.parentFolderIdField;
	}

	/**
	 * Sets the parent folder id.
	 *
	 * @param value the new parent folder id
	 */
	public final void setparentFolderId(String value) {
		this.parentFolderIdField = value;
	}

	/**
	 * Gets the folder type.
	 *
	 * @return the folder type
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public FolderTypeXml folderType
	public final FolderTypeXml getfolderType() {
		return this.folderTypeField;
	}

	/**
	 * Sets the folder type.
	 *
	 * @param value the new folder type
	 */
	public final void setfolderType(FolderTypeXml value) {
		this.folderTypeField = value;
	}

	/**
	 * Gets the update user.
	 *
	 * @return the update user
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string updateUser
	public final String getupdateUser() {
		return this.updateUserField;
	}

	/**
	 * Sets the update user.
	 *
	 * @param value the new update user
	 */
	public final void setupdateUser(String value) {
		this.updateUserField = value;
	}

}