package com.onloupe.core.server.data;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class FoldersListXml.
 */
public class FoldersListXml {

	/** The folders field. */
	private FolderXml[] foldersField;

	/** The version field. */
	private long versionField;

	/**
	 * Instantiates a new folders list xml.
	 */
	public FoldersListXml() {
		this.versionField = ((0));
	}

	/**
	 * Gets the folders.
	 *
	 * @return the folders
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("folder", IsNullable=false)] public FolderXml[] folders
	public final FolderXml[] getfolders() {
		return this.foldersField;
	}

	/**
	 * Sets the folders.
	 *
	 * @param value the new folders
	 */
	public final void setfolders(FolderXml[] value) {
		this.foldersField = value;
	}

	/**
	 * Gets the version.
	 *
	 * @return the version
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()][System.ComponentModel.DefaultValueAttribute(typeof(long), "0")] public long version
	public final long getversion() {
		return this.versionField;
	}

	/**
	 * Sets the version.
	 *
	 * @param value the new version
	 */
	public final void setversion(long value) {
		this.versionField = value;
	}

}