package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

public class FoldersListXml {

	private FolderXml[] foldersField;

	private long versionField;

	public FoldersListXml() {
		this.versionField = ((0));
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("folder", IsNullable=false)] public FolderXml[] folders
	public final FolderXml[] getfolders() {
		return this.foldersField;
	}

	public final void setfolders(FolderXml[] value) {
		this.foldersField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()][System.ComponentModel.DefaultValueAttribute(typeof(long), "0")] public long version
	public final long getversion() {
		return this.versionField;
	}

	public final void setversion(long value) {
		this.versionField = value;
	}

}