package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class HubConfigurationXml.
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")][System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd", IsNullable=false)] public partial class HubConfigurationXml: object, System.ComponentModel.INotifyPropertyChanged
public class HubConfigurationXml {

	/** The expiration dt field. */
	private DateTimeOffsetXml expirationDtField;

	/** The mailbox field. */
	private RepositoryMailboxXml mailboxField;

	/** The client repositories field. */
	private ClientRepositoryXml[] clientRepositoriesField;

	/** The public key field. */
	private String publicKeyField;

	/** The live stream field. */
	private LiveStreamServerXml liveStreamField;

	/** The redirect requested field. */
	private boolean redirectRequestedField;

	/** The status field. */
	private HubStatusXml statusField = HubStatusXml.values()[0];

	/** The time to live field. */
	private int timeToLiveField;

	/** The protocol version field. */
	private String protocolVersionField;

	/** The redirect use gibraltar sds field. */
	private boolean redirectUseGibraltarSdsField;

	/** The redirect use gibraltar sds field specified. */
	private boolean redirectUseGibraltarSdsFieldSpecified;

	/** The redirect customer name field. */
	private String redirectCustomerNameField;

	/** The redirect host name field. */
	private String redirectHostNameField;

	/** The redirect port field. */
	private int redirectPortField;

	/** The redirect port field specified. */
	private boolean redirectPortFieldSpecified;

	/** The redirect use ssl field. */
	private boolean redirectUseSslField;

	/** The redirect use ssl field specified. */
	private boolean redirectUseSslFieldSpecified;

	/** The redirect application base directory field. */
	private String redirectApplicationBaseDirectoryField;

	/** The id field. */
	private String idField;

	/**
	 * Gets the expiration dt.
	 *
	 * @return the expiration dt
	 */
	public final DateTimeOffsetXml getexpirationDt() {
		return this.expirationDtField;
	}

	/**
	 * Sets the expiration dt.
	 *
	 * @param value the new expiration dt
	 */
	public final void setexpirationDt(DateTimeOffsetXml value) {
		this.expirationDtField = value;
	}

	/**
	 * Gets the mailbox.
	 *
	 * @return the mailbox
	 */
	public final RepositoryMailboxXml getmailbox() {
		return this.mailboxField;
	}

	/**
	 * Sets the mailbox.
	 *
	 * @param value the new mailbox
	 */
	public final void setmailbox(RepositoryMailboxXml value) {
		this.mailboxField = value;
	}

	/**
	 * Gets the client repositories.
	 *
	 * @return the client repositories
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("clientRepository", IsNullable=false)] public ClientRepositoryXml[] clientRepositories
	public final ClientRepositoryXml[] getclientRepositories() {
		return this.clientRepositoriesField;
	}

	/**
	 * Sets the client repositories.
	 *
	 * @param value the new client repositories
	 */
	public final void setclientRepositories(ClientRepositoryXml[] value) {
		this.clientRepositoriesField = value;
	}

	/**
	 * Gets the public key.
	 *
	 * @return the public key
	 */
	public final String getpublicKey() {
		return this.publicKeyField;
	}

	/**
	 * Sets the public key.
	 *
	 * @param value the new public key
	 */
	public final void setpublicKey(String value) {
		this.publicKeyField = value;
	}

	/**
	 * Gets the live stream.
	 *
	 * @return the live stream
	 */
	public final LiveStreamServerXml getliveStream() {
		return this.liveStreamField;
	}

	/**
	 * Sets the live stream.
	 *
	 * @param value the new live stream
	 */
	public final void setliveStream(LiveStreamServerXml value) {
		this.liveStreamField = value;
	}

	/**
	 * Gets the redirect requested.
	 *
	 * @return the redirect requested
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectRequested
	public final boolean getredirectRequested() {
		return this.redirectRequestedField;
	}

	/**
	 * Sets the redirect requested.
	 *
	 * @param value the new redirect requested
	 */
	public final void setredirectRequested(boolean value) {
		this.redirectRequestedField = value;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public HubStatusXml status
	public final HubStatusXml getstatus() {
		return this.statusField;
	}

	/**
	 * Sets the status.
	 *
	 * @param value the new status
	 */
	public final void setstatus(HubStatusXml value) {
		this.statusField = value;
	}

	/**
	 * Gets the time to live.
	 *
	 * @return the time to live
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int timeToLive
	public final int gettimeToLive() {
		return this.timeToLiveField;
	}

	/**
	 * Sets the time to live.
	 *
	 * @param value the new time to live
	 */
	public final void settimeToLive(int value) {
		this.timeToLiveField = value;
	}

	/**
	 * Gets the protocol version.
	 *
	 * @return the protocol version
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string protocolVersion
	public final String getprotocolVersion() {
		return this.protocolVersionField;
	}

	/**
	 * Sets the protocol version.
	 *
	 * @param value the new protocol version
	 */
	public final void setprotocolVersion(String value) {
		this.protocolVersionField = value;
	}

	/**
	 * Gets the redirect use gibraltar sds.
	 *
	 * @return the redirect use gibraltar sds
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectUseGibraltarSds
	public final boolean getredirectUseGibraltarSds() {
		return this.redirectUseGibraltarSdsField;
	}

	/**
	 * Sets the redirect use gibraltar sds.
	 *
	 * @param value the new redirect use gibraltar sds
	 */
	public final void setredirectUseGibraltarSds(boolean value) {
		this.redirectUseGibraltarSdsField = value;
	}

	/**
	 * Gets the redirect use gibraltar sds specified.
	 *
	 * @return the redirect use gibraltar sds specified
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectUseGibraltarSdsSpecified
	public final boolean getredirectUseGibraltarSdsSpecified() {
		return this.redirectUseGibraltarSdsFieldSpecified;
	}

	/**
	 * Sets the redirect use gibraltar sds specified.
	 *
	 * @param value the new redirect use gibraltar sds specified
	 */
	public final void setredirectUseGibraltarSdsSpecified(boolean value) {
		this.redirectUseGibraltarSdsFieldSpecified = value;
	}

	/**
	 * Gets the redirect customer name.
	 *
	 * @return the redirect customer name
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectCustomerName
	public final String getredirectCustomerName() {
		return this.redirectCustomerNameField;
	}

	/**
	 * Sets the redirect customer name.
	 *
	 * @param value the new redirect customer name
	 */
	public final void setredirectCustomerName(String value) {
		this.redirectCustomerNameField = value;
	}

	/**
	 * Gets the redirect host name.
	 *
	 * @return the redirect host name
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectHostName
	public final String getredirectHostName() {
		return this.redirectHostNameField;
	}

	/**
	 * Sets the redirect host name.
	 *
	 * @param value the new redirect host name
	 */
	public final void setredirectHostName(String value) {
		this.redirectHostNameField = value;
	}

	/**
	 * Gets the redirect port.
	 *
	 * @return the redirect port
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int redirectPort
	public final int getredirectPort() {
		return this.redirectPortField;
	}

	/**
	 * Sets the redirect port.
	 *
	 * @param value the new redirect port
	 */
	public final void setredirectPort(int value) {
		this.redirectPortField = value;
	}

	/**
	 * Gets the redirect port specified.
	 *
	 * @return the redirect port specified
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectPortSpecified
	public final boolean getredirectPortSpecified() {
		return this.redirectPortFieldSpecified;
	}

	/**
	 * Sets the redirect port specified.
	 *
	 * @param value the new redirect port specified
	 */
	public final void setredirectPortSpecified(boolean value) {
		this.redirectPortFieldSpecified = value;
	}

	/**
	 * Gets the redirect use ssl.
	 *
	 * @return the redirect use ssl
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectUseSsl
	public final boolean getredirectUseSsl() {
		return this.redirectUseSslField;
	}

	/**
	 * Sets the redirect use ssl.
	 *
	 * @param value the new redirect use ssl
	 */
	public final void setredirectUseSsl(boolean value) {
		this.redirectUseSslField = value;
	}

	/**
	 * Gets the redirect use ssl specified.
	 *
	 * @return the redirect use ssl specified
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectUseSslSpecified
	public final boolean getredirectUseSslSpecified() {
		return this.redirectUseSslFieldSpecified;
	}

	/**
	 * Sets the redirect use ssl specified.
	 *
	 * @param value the new redirect use ssl specified
	 */
	public final void setredirectUseSslSpecified(boolean value) {
		this.redirectUseSslFieldSpecified = value;
	}

	/**
	 * Gets the redirect application base directory.
	 *
	 * @return the redirect application base directory
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectApplicationBaseDirectory
	public final String getredirectApplicationBaseDirectory() {
		return this.redirectApplicationBaseDirectoryField;
	}

	/**
	 * Sets the redirect application base directory.
	 *
	 * @param value the new redirect application base directory
	 */
	public final void setredirectApplicationBaseDirectory(String value) {
		this.redirectApplicationBaseDirectoryField = value;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	/**
	 * Sets the id.
	 *
	 * @param value the new id
	 */
	public final void setid(String value) {
		this.idField = value;
	}

}