package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")][System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd", IsNullable=false)] public partial class HubConfigurationXml: object, System.ComponentModel.INotifyPropertyChanged
public class HubConfigurationXml {

	private DateTimeOffsetXml expirationDtField;

	private RepositoryMailboxXml mailboxField;

	private ClientRepositoryXml[] clientRepositoriesField;

	private String publicKeyField;

	private LiveStreamServerXml liveStreamField;

	private boolean redirectRequestedField;

	private HubStatusXml statusField = HubStatusXml.values()[0];

	private int timeToLiveField;

	private String protocolVersionField;

	private boolean redirectUseGibraltarSdsField;

	private boolean redirectUseGibraltarSdsFieldSpecified;

	private String redirectCustomerNameField;

	private String redirectHostNameField;

	private int redirectPortField;

	private boolean redirectPortFieldSpecified;

	private boolean redirectUseSslField;

	private boolean redirectUseSslFieldSpecified;

	private String redirectApplicationBaseDirectoryField;

	private String idField;

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getexpirationDt() {
		return this.expirationDtField;
	}

	public final void setexpirationDt(DateTimeOffsetXml value) {
		this.expirationDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final RepositoryMailboxXml getmailbox() {
		return this.mailboxField;
	}

	public final void setmailbox(RepositoryMailboxXml value) {
		this.mailboxField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("clientRepository", IsNullable=false)] public ClientRepositoryXml[] clientRepositories
	public final ClientRepositoryXml[] getclientRepositories() {
		return this.clientRepositoriesField;
	}

	public final void setclientRepositories(ClientRepositoryXml[] value) {
		this.clientRepositoriesField = value;
	}

	/**
	 * <remarks/>
	 */
	public final String getpublicKey() {
		return this.publicKeyField;
	}

	public final void setpublicKey(String value) {
		this.publicKeyField = value;
	}

	/**
	 * <remarks/>
	 */
	public final LiveStreamServerXml getliveStream() {
		return this.liveStreamField;
	}

	public final void setliveStream(LiveStreamServerXml value) {
		this.liveStreamField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectRequested
	public final boolean getredirectRequested() {
		return this.redirectRequestedField;
	}

	public final void setredirectRequested(boolean value) {
		this.redirectRequestedField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public HubStatusXml status
	public final HubStatusXml getstatus() {
		return this.statusField;
	}

	public final void setstatus(HubStatusXml value) {
		this.statusField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int timeToLive
	public final int gettimeToLive() {
		return this.timeToLiveField;
	}

	public final void settimeToLive(int value) {
		this.timeToLiveField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string protocolVersion
	public final String getprotocolVersion() {
		return this.protocolVersionField;
	}

	public final void setprotocolVersion(String value) {
		this.protocolVersionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectUseGibraltarSds
	public final boolean getredirectUseGibraltarSds() {
		return this.redirectUseGibraltarSdsField;
	}

	public final void setredirectUseGibraltarSds(boolean value) {
		this.redirectUseGibraltarSdsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectUseGibraltarSdsSpecified
	public final boolean getredirectUseGibraltarSdsSpecified() {
		return this.redirectUseGibraltarSdsFieldSpecified;
	}

	public final void setredirectUseGibraltarSdsSpecified(boolean value) {
		this.redirectUseGibraltarSdsFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectCustomerName
	public final String getredirectCustomerName() {
		return this.redirectCustomerNameField;
	}

	public final void setredirectCustomerName(String value) {
		this.redirectCustomerNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectHostName
	public final String getredirectHostName() {
		return this.redirectHostNameField;
	}

	public final void setredirectHostName(String value) {
		this.redirectHostNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int redirectPort
	public final int getredirectPort() {
		return this.redirectPortField;
	}

	public final void setredirectPort(int value) {
		this.redirectPortField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectPortSpecified
	public final boolean getredirectPortSpecified() {
		return this.redirectPortFieldSpecified;
	}

	public final void setredirectPortSpecified(boolean value) {
		this.redirectPortFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool redirectUseSsl
	public final boolean getredirectUseSsl() {
		return this.redirectUseSslField;
	}

	public final void setredirectUseSsl(boolean value) {
		this.redirectUseSslField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool redirectUseSslSpecified
	public final boolean getredirectUseSslSpecified() {
		return this.redirectUseSslFieldSpecified;
	}

	public final void setredirectUseSslSpecified(boolean value) {
		this.redirectUseSslFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string redirectApplicationBaseDirectory
	public final String getredirectApplicationBaseDirectory() {
		return this.redirectApplicationBaseDirectoryField;
	}

	public final void setredirectApplicationBaseDirectory(String value) {
		this.redirectApplicationBaseDirectoryField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

}