package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class LiveStreamServerXml.
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class LiveStreamServerXml: object, System.ComponentModel.INotifyPropertyChanged
public class LiveStreamServerXml {

	/** The agent port field. */
	private int agentPortField;

	/** The client port field. */
	private int clientPortField;

	/** The use ssl field. */
	private boolean useSslField;

	/**
	 * Gets the agent port.
	 *
	 * @return the agent port
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int agentPort
	public final int getagentPort() {
		return this.agentPortField;
	}

	/**
	 * Sets the agent port.
	 *
	 * @param value the new agent port
	 */
	public final void setagentPort(int value) {
		this.agentPortField = value;
	}

	/**
	 * Gets the client port.
	 *
	 * @return the client port
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int clientPort
	public final int getclientPort() {
		return this.clientPortField;
	}

	/**
	 * Sets the client port.
	 *
	 * @param value the new client port
	 */
	public final void setclientPort(int value) {
		this.clientPortField = value;
	}

	/**
	 * Gets the use ssl.
	 *
	 * @return the use ssl
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool useSsl
	public final boolean getuseSsl() {
		return this.useSslField;
	}

	/**
	 * Sets the use ssl.
	 *
	 * @param value the new use ssl
	 */
	public final void setuseSsl(boolean value) {
		this.useSslField = value;
	}

}