package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class LogMessageCategoryXml: object, System.ComponentModel.INotifyPropertyChanged
public class LogMessageCategoryXml {

	private String idField;

	private LogMessageSeverityXml severityField = LogMessageSeverityXml.values()[0];

	private String categoryField;

	private String captionField;

	private int messageCountField;

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public LogMessageSeverityXml severity
	public final LogMessageSeverityXml getseverity() {
		return this.severityField;
	}

	public final void setseverity(LogMessageSeverityXml value) {
		this.severityField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string category
	public final String getcategory() {
		return this.categoryField;
	}

	public final void setcategory(String value) {
		this.categoryField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string caption
	public final String getcaption() {
		return this.captionField;
	}

	public final void setcaption(String value) {
		this.captionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int messageCount
	public final int getmessageCount() {
		return this.messageCountField;
	}

	public final void setmessageCount(int value) {
		this.messageCountField = value;
	}

}