package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public enum LogMessageSeverityXml
public enum LogMessageSeverityXml {

	/**
	 * <remarks/>
	 */
	VERBOSE,

	/**
	 * <remarks/>
	 */
	INFORMATION,

	/**
	 * <remarks/>
	 */
	WARNING,

	/**
	 * <remarks/>
	 */
	ERROR,

	/**
	 * <remarks/>
	 */
	CRITICAL;

	public static final int SIZE = java.lang.Integer.SIZE;

	public int getValue() {
		return this.ordinal();
	}

	public static LogMessageSeverityXml forValue(int value) {
		return values()[value];
	}
}