package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class RepositoryMailboxTrackingXml: object, System.ComponentModel.INotifyPropertyChanged
public class RepositoryMailboxTrackingXml {

	private String statusMessageField;

	private DateTimeOffsetXml lastContactDtField;

	private DateTimeOffsetXml updatedDtField;

	private boolean inErrorField;

	/**
	 * <remarks/>
	 */
	public final String getstatusMessage() {
		return this.statusMessageField;
	}

	public final void setstatusMessage(String value) {
		this.statusMessageField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getlastContactDt() {
		return this.lastContactDtField;
	}

	public final void setlastContactDt(DateTimeOffsetXml value) {
		this.lastContactDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getupdatedDt() {
		return this.updatedDtField;
	}

	public final void setupdatedDt(DateTimeOffsetXml value) {
		this.updatedDtField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool inError
	public final boolean getinError() {
		return this.inErrorField;
	}

	public final void setinError(boolean value) {
		this.inErrorField = value;
	}

}