package com.onloupe.core.server.data;

import java.time.LocalDateTime;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class RepositorySubmissionMetricXml: object, System.ComponentModel.INotifyPropertyChanged
public class RepositorySubmissionMetricXml {

	private String idField;

	private LocalDateTime dateField = LocalDateTime.MIN;

	private int sessionsField;

	private int criticalSessionsField;

	private int errorSessionsField;

	private int uniqueHostsField;

	private long bytesReceivedField;

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")] public System.DateTime date
	public final LocalDateTime getdate() {
		return this.dateField;
	}

	public final void setdate(LocalDateTime value) {
		this.dateField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int sessions
	public final int getsessions() {
		return this.sessionsField;
	}

	public final void setsessions(int value) {
		this.sessionsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int criticalSessions
	public final int getcriticalSessions() {
		return this.criticalSessionsField;
	}

	public final void setcriticalSessions(int value) {
		this.criticalSessionsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int errorSessions
	public final int geterrorSessions() {
		return this.errorSessionsField;
	}

	public final void seterrorSessions(int value) {
		this.errorSessionsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int uniqueHosts
	public final int getuniqueHosts() {
		return this.uniqueHostsField;
	}

	public final void setuniqueHosts(int value) {
		this.uniqueHostsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long bytesReceived
	public final long getbytesReceived() {
		return this.bytesReceivedField;
	}

	public final void setbytesReceived(long value) {
		this.bytesReceivedField = value;
	}

}