package com.onloupe.core.server.data;

import java.time.LocalDateTime;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class RepositorySubmissionMetricXml.
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class RepositorySubmissionMetricXml: object, System.ComponentModel.INotifyPropertyChanged
public class RepositorySubmissionMetricXml {

	/** The id field. */
	private String idField;

	/** The date field. */
	private LocalDateTime dateField = LocalDateTime.MIN;

	/** The sessions field. */
	private int sessionsField;

	/** The critical sessions field. */
	private int criticalSessionsField;

	/** The error sessions field. */
	private int errorSessionsField;

	/** The unique hosts field. */
	private int uniqueHostsField;

	/** The bytes received field. */
	private long bytesReceivedField;

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	/**
	 * Sets the id.
	 *
	 * @param value the new id
	 */
	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * Gets the date.
	 *
	 * @return the date
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")] public System.DateTime date
	public final LocalDateTime getdate() {
		return this.dateField;
	}

	/**
	 * Sets the date.
	 *
	 * @param value the new date
	 */
	public final void setdate(LocalDateTime value) {
		this.dateField = value;
	}

	/**
	 * Gets the sessions.
	 *
	 * @return the sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int sessions
	public final int getsessions() {
		return this.sessionsField;
	}

	/**
	 * Sets the sessions.
	 *
	 * @param value the new sessions
	 */
	public final void setsessions(int value) {
		this.sessionsField = value;
	}

	/**
	 * Gets the critical sessions.
	 *
	 * @return the critical sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int criticalSessions
	public final int getcriticalSessions() {
		return this.criticalSessionsField;
	}

	/**
	 * Sets the critical sessions.
	 *
	 * @param value the new critical sessions
	 */
	public final void setcriticalSessions(int value) {
		this.criticalSessionsField = value;
	}

	/**
	 * Gets the error sessions.
	 *
	 * @return the error sessions
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int errorSessions
	public final int geterrorSessions() {
		return this.errorSessionsField;
	}

	/**
	 * Sets the error sessions.
	 *
	 * @param value the new error sessions
	 */
	public final void seterrorSessions(int value) {
		this.errorSessionsField = value;
	}

	/**
	 * Gets the unique hosts.
	 *
	 * @return the unique hosts
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int uniqueHosts
	public final int getuniqueHosts() {
		return this.uniqueHostsField;
	}

	/**
	 * Sets the unique hosts.
	 *
	 * @param value the new unique hosts
	 */
	public final void setuniqueHosts(int value) {
		this.uniqueHostsField = value;
	}

	/**
	 * Gets the bytes received.
	 *
	 * @return the bytes received
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long bytesReceived
	public final long getbytesReceived() {
		return this.bytesReceivedField;
	}

	/**
	 * Sets the bytes received.
	 *
	 * @param value the new bytes received
	 */
	public final void setbytesReceived(long value) {
		this.bytesReceivedField = value;
	}

}