package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")][System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd", IsNullable=false)] public partial class RepositorySubscriptionXml: object, System.ComponentModel.INotifyPropertyChanged
public class RepositorySubscriptionXml {

	private DateTimeOffsetXml addedDtField;

	private String idField;

	private String serverRepositoryIdField;

	private String computerKeyField;

	private boolean useGibraltarSdsField;

	private String customerNameField;

	private String hostNameField;

	private int portField;

	private boolean portFieldSpecified;

	private boolean useSslField;

	private boolean useSslFieldSpecified;

	private String applicationBaseDirectoryField;

	private String repositoryField;

	private SessionSynchronizationModeXml syncModeField;

	private boolean useApiKeyField;

	private boolean useApiKeyFieldSpecified;

	private String userNameField;

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getaddedDt() {
		return this.addedDtField;
	}

	public final void setaddedDt(DateTimeOffsetXml value) {
		this.addedDtField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string serverRepositoryId
	public final String getserverRepositoryId() {
		return this.serverRepositoryIdField;
	}

	public final void setserverRepositoryId(String value) {
		this.serverRepositoryIdField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string computerKey
	public final String getcomputerKey() {
		return this.computerKeyField;
	}

	public final void setcomputerKey(String value) {
		this.computerKeyField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool useGibraltarSds
	public final boolean getuseGibraltarSds() {
		return this.useGibraltarSdsField;
	}

	public final void setuseGibraltarSds(boolean value) {
		this.useGibraltarSdsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string customerName
	public final String getcustomerName() {
		return this.customerNameField;
	}

	public final void setcustomerName(String value) {
		this.customerNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string hostName
	public final String gethostName() {
		return this.hostNameField;
	}

	public final void sethostName(String value) {
		this.hostNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int port
	public final int getport() {
		return this.portField;
	}

	public final void setport(int value) {
		this.portField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool portSpecified
	public final boolean getportSpecified() {
		return this.portFieldSpecified;
	}

	public final void setportSpecified(boolean value) {
		this.portFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool useSsl
	public final boolean getuseSsl() {
		return this.useSslField;
	}

	public final void setuseSsl(boolean value) {
		this.useSslField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool useSslSpecified
	public final boolean getuseSslSpecified() {
		return this.useSslFieldSpecified;
	}

	public final void setuseSslSpecified(boolean value) {
		this.useSslFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string applicationBaseDirectory
	public final String getapplicationBaseDirectory() {
		return this.applicationBaseDirectoryField;
	}

	public final void setapplicationBaseDirectory(String value) {
		this.applicationBaseDirectoryField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string repository
	public final String getrepository() {
		return this.repositoryField;
	}

	public final void setrepository(String value) {
		this.repositoryField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public SessionSynchronizationModeXml syncMode
	public final SessionSynchronizationModeXml getsyncMode() {
		return this.syncModeField;
	}

	public final void setsyncMode(SessionSynchronizationModeXml value) {
		this.syncModeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool useApiKey
	public final boolean getuseApiKey() {
		return this.useApiKeyField;
	}

	public final void setuseApiKey(boolean value) {
		this.useApiKeyField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool useApiKeySpecified
	public final boolean getuseApiKeySpecified() {
		return this.useApiKeyFieldSpecified;
	}

	public final void setuseApiKeySpecified(boolean value) {
		this.useApiKeyFieldSpecified = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string userName
	public final String getuserName() {
		return this.userNameField;
	}

	public final void setuserName(String value) {
		this.userNameField = value;
	}

}