package com.onloupe.core.server.data;

// TODO: Auto-generated Javadoc
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class RepositorySubscriptionStateXml.
 */

/** 
*/

/** 
*/

/** 
*/

/**
 * 
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")][System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd", IsNullable=false)] public partial class RepositorySubscriptionStateXml: object, System.ComponentModel.INotifyPropertyChanged
public class RepositorySubscriptionStateXml {

	/** The last contact dt field. */
	private DateTimeOffsetXml lastContactDtField;

	/** The sessions version field. */
	private long sessionsVersionField;

	/** The sessions data version field. */
	private long sessionsDataVersionField;

	/**
	 * Gets the last contact dt.
	 *
	 * @return the last contact dt
	 */
	public final DateTimeOffsetXml getlastContactDt() {
		return this.lastContactDtField;
	}

	/**
	 * Sets the last contact dt.
	 *
	 * @param value the new last contact dt
	 */
	public final void setlastContactDt(DateTimeOffsetXml value) {
		this.lastContactDtField = value;
	}

	/**
	 * Gets the sessions version.
	 *
	 * @return the sessions version
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long sessionsVersion
	public final long getsessionsVersion() {
		return this.sessionsVersionField;
	}

	/**
	 * Sets the sessions version.
	 *
	 * @param value the new sessions version
	 */
	public final void setsessionsVersion(long value) {
		this.sessionsVersionField = value;
	}

	/**
	 * Gets the sessions data version.
	 *
	 * @return the sessions data version
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long sessionsDataVersion
	public final long getsessionsDataVersion() {
		return this.sessionsDataVersionField;
	}

	/**
	 * Sets the sessions data version.
	 *
	 * @param value the new sessions data version
	 */
	public final void setsessionsDataVersion(long value) {
		this.sessionsDataVersionField = value;
	}

}