package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class SessionDetailXml: object, System.ComponentModel.INotifyPropertyChanged
public class SessionDetailXml {

	private DateTimeOffsetXml startDtField;

	private DateTimeOffsetXml endDtField;

	private DateTimeOffsetXml addedDtField;

	private DateTimeOffsetXml updatedDtField;

	private SessionPropertyXml[] propertiesField;

	private LogMessageCategoryXml[] logMessageCategoriesField;

	private LogMessageClassXml[] logMessageClassesField;

	private String productNameField;

	private String applicationNameField;

	private String environmentNameField;

	private String promotionLevelNameField;

	private String applicationVersionField;

	private ApplicationTypeXml applicationTypeField = ApplicationTypeXml.values()[0];

	private String applicationDescriptionField;

	private String captionField;

	private SessionStatusXml statusField = SessionStatusXml.values()[0];

	private String timeZoneCaptionField;

	private long durationSecField;

	private String agentVersionField;

	private String userNameField;

	private String userDomainNameField;

	private String hostNameField;

	private String dnsDomainNameField;

	private boolean isNewField;

	private boolean isCompleteField;

	private int messageCountField;

	private int criticalMessageCountField;

	private int errorMessageCountField;

	private int warningMessageCountField;

	private String updateUserField;

	private int osPlatformCodeField;

	private String osVersionField;

	private String osServicePackField;

	private String osCultureNameField;

	private ProcessorArchitectureXml osArchitectureField = ProcessorArchitectureXml.values()[0];

	private BootModeXml osBootModeField = BootModeXml.values()[0];

	private int osSuiteMaskCodeField;

	private int osProductTypeCodeField;

	private String runtimeVersionField;

	private ProcessorArchitectureXml runtimeArchitectureField = ProcessorArchitectureXml.values()[0];

	private String currentCultureNameField;

	private String currentUiCultureNameField;

	private int memoryMbField;

	private int processorsField;

	private int processorCoresField;

	private boolean userInteractiveField;

	private boolean terminalServerField;

	private int screenWidthField;

	private int screenHeightField;

	private int colorDepthField;

	private String commandLineField;

	private long fileSizeField;

	private boolean fileAvailableField;

	private String computerIdField;

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getstartDt() {
		return this.startDtField;
	}

	public final void setstartDt(DateTimeOffsetXml value) {
		this.startDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getendDt() {
		return this.endDtField;
	}

	public final void setendDt(DateTimeOffsetXml value) {
		this.endDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getaddedDt() {
		return this.addedDtField;
	}

	public final void setaddedDt(DateTimeOffsetXml value) {
		this.addedDtField = value;
	}

	/**
	 * <remarks/>
	 */
	public final DateTimeOffsetXml getupdatedDt() {
		return this.updatedDtField;
	}

	public final void setupdatedDt(DateTimeOffsetXml value) {
		this.updatedDtField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("property", IsNullable=false)] public SessionPropertyXml[] properties
	public final SessionPropertyXml[] getproperties() {
		return this.propertiesField;
	}

	public final void setproperties(SessionPropertyXml[] value) {
		this.propertiesField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("logMessageCategory", IsNullable=false)] public LogMessageCategoryXml[] logMessageCategories
	public final LogMessageCategoryXml[] getlogMessageCategories() {
		return this.logMessageCategoriesField;
	}

	public final void setlogMessageCategories(LogMessageCategoryXml[] value) {
		this.logMessageCategoriesField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("logMessageClass", IsNullable=false)] public LogMessageClassXml[] logMessageClasses
	public final LogMessageClassXml[] getlogMessageClasses() {
		return this.logMessageClassesField;
	}

	public final void setlogMessageClasses(LogMessageClassXml[] value) {
		this.logMessageClassesField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string productName
	public final String getproductName() {
		return this.productNameField;
	}

	public final void setproductName(String value) {
		this.productNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string applicationName
	public final String getapplicationName() {
		return this.applicationNameField;
	}

	public final void setapplicationName(String value) {
		this.applicationNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string environmentName
	public final String getenvironmentName() {
		return this.environmentNameField;
	}

	public final void setenvironmentName(String value) {
		this.environmentNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string promotionLevelName
	public final String getpromotionLevelName() {
		return this.promotionLevelNameField;
	}

	public final void setpromotionLevelName(String value) {
		this.promotionLevelNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string applicationVersion
	public final String getapplicationVersion() {
		return this.applicationVersionField;
	}

	public final void setapplicationVersion(String value) {
		this.applicationVersionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public ApplicationTypeXml applicationType
	public final ApplicationTypeXml getapplicationType() {
		return this.applicationTypeField;
	}

	public final void setapplicationType(ApplicationTypeXml value) {
		this.applicationTypeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string applicationDescription
	public final String getapplicationDescription() {
		return this.applicationDescriptionField;
	}

	public final void setapplicationDescription(String value) {
		this.applicationDescriptionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string caption
	public final String getcaption() {
		return this.captionField;
	}

	public final void setcaption(String value) {
		this.captionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public SessionStatusXml status
	public final SessionStatusXml getstatus() {
		return this.statusField;
	}

	public final void setstatus(SessionStatusXml value) {
		this.statusField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string timeZoneCaption
	public final String gettimeZoneCaption() {
		return this.timeZoneCaptionField;
	}

	public final void settimeZoneCaption(String value) {
		this.timeZoneCaptionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string agentVersion
	public final String getagentVersion() {
		return this.agentVersionField;
	}

	public final void setagentVersion(String value) {
		this.agentVersionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string userName
	public final String getuserName() {
		return this.userNameField;
	}

	public final void setuserName(String value) {
		this.userNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string userDomainName
	public final String getuserDomainName() {
		return this.userDomainNameField;
	}

	public final void setuserDomainName(String value) {
		this.userDomainNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string hostName
	public final String gethostName() {
		return this.hostNameField;
	}

	public final void sethostName(String value) {
		this.hostNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string dnsDomainName
	public final String getdnsDomainName() {
		return this.dnsDomainNameField;
	}

	public final void setdnsDomainName(String value) {
		this.dnsDomainNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool isNew
	public final boolean getisNew() {
		return this.isNewField;
	}

	public final void setisNew(boolean value) {
		this.isNewField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool isComplete
	public final boolean getisComplete() {
		return this.isCompleteField;
	}

	public final void setisComplete(boolean value) {
		this.isCompleteField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int messageCount
	public final int getmessageCount() {
		return this.messageCountField;
	}

	public final void setmessageCount(int value) {
		this.messageCountField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int criticalMessageCount
	public final int getcriticalMessageCount() {
		return this.criticalMessageCountField;
	}

	public final void setcriticalMessageCount(int value) {
		this.criticalMessageCountField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int errorMessageCount
	public final int geterrorMessageCount() {
		return this.errorMessageCountField;
	}

	public final void seterrorMessageCount(int value) {
		this.errorMessageCountField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int warningMessageCount
	public final int getwarningMessageCount() {
		return this.warningMessageCountField;
	}

	public final void setwarningMessageCount(int value) {
		this.warningMessageCountField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string updateUser
	public final String getupdateUser() {
		return this.updateUserField;
	}

	public final void setupdateUser(String value) {
		this.updateUserField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int osPlatformCode
	public final int getosPlatformCode() {
		return this.osPlatformCodeField;
	}

	public final void setosPlatformCode(int value) {
		this.osPlatformCodeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string osVersion
	public final String getosVersion() {
		return this.osVersionField;
	}

	public final void setosVersion(String value) {
		this.osVersionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string osServicePack
	public final String getosServicePack() {
		return this.osServicePackField;
	}

	public final void setosServicePack(String value) {
		this.osServicePackField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string osCultureName
	public final String getosCultureName() {
		return this.osCultureNameField;
	}

	public final void setosCultureName(String value) {
		this.osCultureNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public ProcessorArchitectureXml osArchitecture
	public final ProcessorArchitectureXml getosArchitecture() {
		return this.osArchitectureField;
	}

	public final void setosArchitecture(ProcessorArchitectureXml value) {
		this.osArchitectureField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public BootModeXml osBootMode
	public final BootModeXml getosBootMode() {
		return this.osBootModeField;
	}

	public final void setosBootMode(BootModeXml value) {
		this.osBootModeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int osSuiteMaskCode
	public final int getosSuiteMaskCode() {
		return this.osSuiteMaskCodeField;
	}

	public final void setosSuiteMaskCode(int value) {
		this.osSuiteMaskCodeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int osProductTypeCode
	public final int getosProductTypeCode() {
		return this.osProductTypeCodeField;
	}

	public final void setosProductTypeCode(int value) {
		this.osProductTypeCodeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string runtimeVersion
	public final String getruntimeVersion() {
		return this.runtimeVersionField;
	}

	public final void setruntimeVersion(String value) {
		this.runtimeVersionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public ProcessorArchitectureXml runtimeArchitecture
	public final ProcessorArchitectureXml getruntimeArchitecture() {
		return this.runtimeArchitectureField;
	}

	public final void setruntimeArchitecture(ProcessorArchitectureXml value) {
		this.runtimeArchitectureField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string currentCultureName
	public final String getcurrentCultureName() {
		return this.currentCultureNameField;
	}

	public final void setcurrentCultureName(String value) {
		this.currentCultureNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string currentUiCultureName
	public final String getcurrentUiCultureName() {
		return this.currentUiCultureNameField;
	}

	public final void setcurrentUiCultureName(String value) {
		this.currentUiCultureNameField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int memoryMb
	public final int getmemoryMb() {
		return this.memoryMbField;
	}

	public final void setmemoryMb(int value) {
		this.memoryMbField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int processors
	public final int getprocessors() {
		return this.processorsField;
	}

	public final void setprocessors(int value) {
		this.processorsField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int processorCores
	public final int getprocessorCores() {
		return this.processorCoresField;
	}

	public final void setprocessorCores(int value) {
		this.processorCoresField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool userInteractive
	public final boolean getuserInteractive() {
		return this.userInteractiveField;
	}

	public final void setuserInteractive(boolean value) {
		this.userInteractiveField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool terminalServer
	public final boolean getterminalServer() {
		return this.terminalServerField;
	}

	public final void setterminalServer(boolean value) {
		this.terminalServerField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int screenWidth
	public final int getscreenWidth() {
		return this.screenWidthField;
	}

	public final void setscreenWidth(int value) {
		this.screenWidthField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int screenHeight
	public final int getscreenHeight() {
		return this.screenHeightField;
	}

	public final void setscreenHeight(int value) {
		this.screenHeightField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public int colorDepth
	public final int getcolorDepth() {
		return this.colorDepthField;
	}

	public final void setcolorDepth(int value) {
		this.colorDepthField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string commandLine
	public final String getcommandLine() {
		return this.commandLineField;
	}

	public final void setcommandLine(String value) {
		this.commandLineField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long fileSize
	public final long getfileSize() {
		return this.fileSizeField;
	}

	public final void setfileSize(long value) {
		this.fileSizeField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool fileAvailable
	public final boolean getfileAvailable() {
		return this.fileAvailableField;
	}

	public final void setfileAvailable(boolean value) {
		this.fileAvailableField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string computerId
	public final String getcomputerId() {
		return this.computerIdField;
	}

	public final void setcomputerId(String value) {
		this.computerIdField = value;
	}

	public long getDurationSec() {
		return this.durationSecField;
	}

	public void setDurationSec(long durationSecField) {
		this.durationSecField = durationSecField;
	}

}