package com.onloupe.core.server.data;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/**
 * The Class SessionXml.
 */

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/** 
*/

/**
 * 
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class SessionXml: object, System.ComponentModel.INotifyPropertyChanged
public class SessionXml {

	/** The session detail field. */
	private SessionDetailXml sessionDetailField;

	/** The files field. */
	private SessionFileXml[] filesField;

	/** The id field. */
	private String idField;

	/** The version field. */
	private long versionField;

	/** The deleted field. */
	private boolean deletedField;

	/** The is complete field. */
	private boolean isCompleteField;

	/** The is complete field specified. */
	private boolean isCompleteFieldSpecified;

	/**
	 * Gets the session detail.
	 *
	 * @return the session detail
	 */
	public final SessionDetailXml getsessionDetail() {
		return this.sessionDetailField;
	}

	/**
	 * Sets the session detail.
	 *
	 * @param value the new session detail
	 */
	public final void setsessionDetail(SessionDetailXml value) {
		this.sessionDetailField = value;
	}

	/**
	 * Gets the files.
	 *
	 * @return the files
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)] public SessionFileXml[] files
	public final SessionFileXml[] getfiles() {
		return this.filesField;
	}

	/**
	 * Sets the files.
	 *
	 * @param value the new files
	 */
	public final void setfiles(SessionFileXml[] value) {
		this.filesField = value;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	/**
	 * Sets the id.
	 *
	 * @param value the new id
	 */
	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * Gets the version.
	 *
	 * @return the version
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long version
	public final long getversion() {
		return this.versionField;
	}

	/**
	 * Sets the version.
	 *
	 * @param value the new version
	 */
	public final void setversion(long value) {
		this.versionField = value;
	}

	/**
	 * Gets the deleted.
	 *
	 * @return the deleted
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool deleted
	public final boolean getdeleted() {
		return this.deletedField;
	}

	/**
	 * Sets the deleted.
	 *
	 * @param value the new deleted
	 */
	public final void setdeleted(boolean value) {
		this.deletedField = value;
	}

	/**
	 * Gets the checks if is complete.
	 *
	 * @return the checks if is complete
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool isComplete
	public final boolean getisComplete() {
		return this.isCompleteField;
	}

	/**
	 * Sets the checks if is complete.
	 *
	 * @param value the new checks if is complete
	 */
	public final void setisComplete(boolean value) {
		this.isCompleteField = value;
	}

	/**
	 * Gets the checks if is complete specified.
	 *
	 * @return the checks if is complete specified
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool isCompleteSpecified
	public final boolean getisCompleteSpecified() {
		return this.isCompleteFieldSpecified;
	}

	/**
	 * Sets the checks if is complete specified.
	 *
	 * @param value the new checks if is complete specified
	 */
	public final void setisCompleteSpecified(boolean value) {
		this.isCompleteFieldSpecified = value;
	}

}