package com.onloupe.core.server.data;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/** <remarks/>
*/

/**
 * <remarks/>
 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")][System.Diagnostics.DebuggerStepThroughAttribute()][System.ComponentModel.DesignerCategoryAttribute("code")][System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gibraltarsoftware.com/Gibraltar/Repository.xsd")] public partial class SessionXml: object, System.ComponentModel.INotifyPropertyChanged
public class SessionXml {

	private SessionDetailXml sessionDetailField;

	private SessionFileXml[] filesField;

	private String idField;

	private long versionField;

	private boolean deletedField;

	private boolean isCompleteField;

	private boolean isCompleteFieldSpecified;

	/**
	 * <remarks/>
	 */
	public final SessionDetailXml getsessionDetail() {
		return this.sessionDetailField;
	}

	public final void setsessionDetail(SessionDetailXml value) {
		this.sessionDetailField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)] public SessionFileXml[] files
	public final SessionFileXml[] getfiles() {
		return this.filesField;
	}

	public final void setfiles(SessionFileXml[] value) {
		this.filesField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public string id
	public final String getid() {
		return this.idField;
	}

	public final void setid(String value) {
		this.idField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public long version
	public final long getversion() {
		return this.versionField;
	}

	public final void setversion(long value) {
		this.versionField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool deleted
	public final boolean getdeleted() {
		return this.deletedField;
	}

	public final void setdeleted(boolean value) {
		this.deletedField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlAttributeAttribute()] public bool isComplete
	public final boolean getisComplete() {
		return this.isCompleteField;
	}

	public final void setisComplete(boolean value) {
		this.isCompleteField = value;
	}

	/**
	 * <remarks/>
	 */
//C# TO JAVA CONVERTER TODO TASK: Java annotations will not correspond to .NET attributes:
//ORIGINAL LINE: [System.Xml.Serialization.XmlIgnoreAttribute()] public bool isCompleteSpecified
	public final boolean getisCompleteSpecified() {
		return this.isCompleteFieldSpecified;
	}

	public final void setisCompleteSpecified(boolean value) {
		this.isCompleteFieldSpecified = value;
	}

}